name: iOS Build & Deploy

on:
  workflow_dispatch: # Permite rodar manualmente pelo site do GitHub

jobs:
  deploy:
    name: Build and Deploy iOS
    runs-on: macos-15
    defaults:
      run:
        working-directory: mais-vaquejada
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm cache clean --force
          npm install --force

      - name: Verificar arquivos na nuvem
        run: |
          echo "Verificando se o plugin existe..."
          ls -l node_modules/@capacitor-community/apple-sign-in/Package.swift || echo "ERRO: Plugin não encontrado!"

      - name: Build Web Assets
        run: npm run build

      - name: Capacitor de Sincronização
        working-directory: mais-vaquejada
        run: |
          echo "Sincronizando plugins..."
          npx cap sync ios --deployment
          
      - name: Instale o certificado Apple e o perfil de provisionamento.
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build and Upload to App Store
        working-directory: mais-vaquejada/ios/App
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
        run: |
          # Resolve dependencies inside the iOS folder
          xcodebuild -resolvePackageDependencies
          
          # Build archive
          xcodebuild -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $RUNNER_TEMP/App.xcarchive \
                     archive

          # Export IPA
          xcodebuild -exportArchive \
                     -archivePath $RUNNER_TEMP/App.xcarchive \
                     -exportOptionsPlist App/ExportOptions.plist \
                     -exportPath $RUNNER_TEMP/export \
                     -allowProvisioningUpdates

          # Upload
          xcrun altool --upload-app \
                       --type ios \
                       --file $RUNNER_TEMP/export/App.ipa \
                       --apiKey "$APP_STORE_CONNECT_KEY_ID" \
                       --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID"
